import { useEffect, useState } from "react"
import { Link } from "react-router-dom"
import { clearCanvas } from "../../utils"
import { kite } from "../../shapes/kite"
import { dart } from "../../shapes/dart"
import { polygon } from "../../shapes/polygon"

export const Shapes = ({ canvas }) => {
  const [showKite, setShowKite] = useState(false)
  const [showDart, setShowDart] = useState(false)
  useEffect(() => {
    clearCanvas(canvas)
    return () => clearTimeout(timeout.current)
  }, [])

  const handleDartDrawClick = () => {
    setShowDart(true)
    setShowKite(false)
    clearCanvas(canvas)
    const dartProps = dart({
      depth: 0,
      point: [window.innerWidth / 2, window.innerHeight / 3],
      vector: [0, window.innerHeight / 4],
    })
    dartProps
      .flat(Infinity)
      .forEach((dartProps) => {
        dartProps.fill = '#ccc'
        dartProps.stroke = '#ccc'
        polygon(dartProps)
      })
  }
  const handleKiteDrawClick = () => {
    setShowDart(false)
    setShowKite(true)
    clearCanvas(canvas)
    const kiteProps = kite({
      depth: 0,
      point: [window.innerWidth / 2, window.innerHeight / 3],
      vector: [0, window.innerHeight / 2],
    })
    kiteProps
      .flat(Infinity)
      .forEach((kiteProps) => {
        kiteProps.fill = '#ccc'
        kiteProps.stroke = '#ccc'
        polygon(kiteProps)
      })
  }
  return (
    <>
      <h1>Let's talk about these shapes</h1>
      <article>
        This tiling is generated by drawing kites and darts. {/**/}
        Click below to check out an example of each.
      </article>

      <Link to="/explainer/intro"><button>back</button></Link>
      <button onClick={handleKiteDrawClick}>kite</button>
      <button onClick={handleDartDrawClick}>dart</button>
      <Link to="/explainer/halfs"><button>next</button></Link>

      {showKite && <article>
        A kite is quadrilateral with three angles of 72° and one of 144°.
      </article>}
      {showDart && <article>
        A dart is a quadrilateral with two angles of 36°, one of 216°, and one of 72°.
      </article>}
    </>
  )
}
